language: ruby
script: bundle exec rspec
rvm:
- 2.4.1
addons:
  code_climate:
    repo_token:
      secure: "bT1akww9+1J6thy0CI3K3DsOPeGlQW6uM8ukys91GKVDNc/6T4IBg4YG5tazUdzfprM7E6tl1WY7qJRl0iXb/6FbEr4iBYSIX4DIs4GBXDOckxSAuIEJIwLRE02nq9R6vzJ4HZmtE247ttVjTB9kRbz6zXnDp9zeImxazJkjmbJGZW0A0QtMBwhbddS9bLm4O6uEwFdDlJJbzRY4xp+REB4fGwVLbDuATT/6dDjiCLReO11IJTn2QyfsCPjH2GpgSF6QKsqns0QckfjbGttjkEH6f2J/pL0g01sQaPLy0I2aHXTnpg7CP0ukYwVQ/VslL4q7k3NI9Zb/h6aa4VP4Ssz6Uh7m9RpkTMohgNI415euLsyGXVvWj5T66vKjHj7LEZJHfLN3byG7X6nXZEjaUUsBbsI9K7aKRWA4JxdlhmPye9PQru6BTkUNpTPQqCNjxZZxyQJ9SgQX+XG5f3B3wsMT4nc8fha5V7j3Dkvxdzu0btYDtyTfg/SAqg91XHf2VAiuw5k9bToLJrTZwop1hJH+vUtOvN3/zzZX+L9WQHnzbKralADFTBBeOIuop9rCygNF1adsd3hJQ5oSHX5IbQ3Y5rNNQGi/MfRao6SGwfV3qq0hpEM9/ZD039hx+1j63yrPym6vCsqgsdjL2OQxqXIyRoOdDCp2/g/nOz75/og="
