language: ruby

rvm:
  - 2.4.1

env:
  global:
    secure: liUrDmSB23V5BAhUDopRnjfWYm2JFs9uqSLPbsA2AXU19ll54mCnFI7WRLy2L84XAteGKlEqis6cvBJ7LmtD/0pdpzvZW9E/QoYU8+NyV8qbAYxXwfWoBwcDufOI2dPbqF3qAmqszulRkBoPNK4yteL+OnV9XsK2FYyVAEQg2ylXOezlBHeEdIXnQsBTTr1Qw8lGZfQdUXhX2/cCMs47ykb2+DplpTsbamqQVVd8zCQwg9yGpMFb8kdAbhopNUqMYPe8v1T9MvfjB03I+7pl9ImmDLKJoS4bWnMF9VMqjsf92qY1vFfzPx06uft3YCycln0icoXao/4uRZ1M5//hLG3t+KT50Pw/9ORA/ZnWg4zLBNr4hZgzuUlQ8F4fFNXLu2E2l0U0Yg7gF0yJzuvIdZO/kKir+y+paVw1uJ4K5Q/K8tQlskPi1/w+YexraJQq4bkrrCGyr/YMcRWD4aptL4ZQd9H7q3VXNTef8uezoHi8YmP86Z9dPwqqFZw0poxHbXmYvX4eXAA3llqsdxUEJIcna9xm/Ycvc/dzMOisonwImdozb6EIxz0d0cGF3CM4WJJ0bNYwk1uRbxBK/CDrgnJ50OaKy+OgL2gAbeT4WUtzkdKdS+pTWpg19ot3hhjIEj04IlWWOVcMSict/MYncpKCVnPefuRC1BEO2EYWSVY=

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
