name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ImageMagick
        run: sudo apt install imagemagick

      - name: Check ImageMagick Version
        run: magick -version

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
          reviewdog_flags: -fail-level=any

      - name: Run RSpec and Code Coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 5b52fdd45b7cb2ac26fd046b36f9480f5b41e7a142dcba9fa31af039c98519cd
        with:
          coverageCommand: bundle exec rspec
