name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Bundle Install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec and Code Coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 5b52fdd45b7cb2ac26fd046b36f9480f5b41e7a142dcba9fa31af039c98519cd
        with:
          coverageCommand: bundle exec rspec
